<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="VSCLPTEST10" ignored="0" name="Default test" tests="2" failures="0" timestamp="23 Nov 2018 11:29:22 GMT" time="27.116" errors="0">
  <testcase name="@BeforeClass openApplication" time="27.069" classname="com.tng.ohrm.OhrmReporting_Extent">
    <failure type="java.lang.AssertionError" message="IsApplicationOpened expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: IsApplicationOpened expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at com.tng.ohrm.OhrmReporting_Extent.openApplication(OhrmReporting_Extent.java:56)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:168)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:105)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- @BeforeClass openApplication -->
  <testcase name="@AfterClass closeApplication" time="0.0" classname="com.tng.ohrm.OhrmReporting_Extent">
    <skipped/>
  </testcase> <!-- @AfterClass closeApplication -->
  <testcase name="login" time="0.001" classname="com.tng.ohrm.OhrmReporting_Extent">
    <skipped/>
  </testcase> <!-- login -->
  <testcase name="addEmployee" time="0.0" classname="com.tng.ohrm.OhrmReporting_Extent">
    <skipped/>
  </testcase> <!-- addEmployee -->
</testsuite> <!-- Default test -->
